FROM ubuntu:16.04

RUN apt update && apt install -y --no-install-recommends python2.7 firefox xvfb \
    && rm -rf /var/lib/apt/lists/*

RUN apt update && apt install -y --no-install-recommends python-pip python-setuptools\
    && pip install --upgrade pip \
    && pip install robotframework robotframework-xvfb robotframework-selenium2library xvfbwrapper \
    && apt remove -y python-pip python-setuptools && rm -rf /var/lib/apt/lists/*

RUN apt update && apt install -y --no-install-recommends wget \
  && wget --quiet https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz \
  && tar xf geckodriver-v0.14.0-linux64.tar.gz && rm -f geckodriver-v0.14.0-linux64.tar.gz \
  && mkdir -p /opt/geckodriver && mv geckodriver /opt/geckodriver \
  && ln -sf /opt/geckodriver/geckodriver /usr/bin/geckodriver \
  && apt remove -y wget && rm -rf /var/lib/apt/lists/*



ENTRYPOINT ["robot"]
