version: '2'

services:
  rocket:
    image: rocket.chat
    ports:
      - 3000:3000
    environment:
      - ROOT_URL:http://localhost
      - MONGO_URL=mongodb://database:27017/meteor
    links:
      - db:database

  db:
    image: mongo:3.0
    command: --smallfiles